# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: example
      # POSTGRES_DB: m7-abp_1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: clinica
    ports:
      - 5432:5432

  adminer:
    image: adminer
    hostname: adminer
    container_name: m5_db_1
    restart: always
    ports:
      - 8080:8080